apiVersion: v1
kind: Pod
metadata:
 name: server-pod
spec:
  containers:
  - name: server-pod
    image: peterchen999/server_111065548:1.0.3
    imagePullPolicy: Never
    ports:
    - containerPort: 8888
    resources:
      requests:
        cpu: "20m"
        memory: "30Mi"
      limits:
        memory: "30Mi"
